### ISSUE TITLE
BioQC::gini cannot handle negative values

### ISSUE THREAD

**Issue by grst** [Accio/BioQC#14]
By definition, gini can only be calculated on positive values. 
The problem can be fixed by shifting/normalizing values. 
Alternatively, an error message should be thrown. Atm. a nonsense value is calculated.

**Comment by Accio** [comment]
An error is raised in such cases, feature added in [82e433ad](https://github.com/Accio/BioQC/commit/82e433ad9443ede7b0e49204adbe33e69c1f27b7)
