### ISSUE TITLE
subsetting a non-existant signature should return an error?

### ISSUE THREAD

**Issue by idavydov** [Accio/BioQC#35]
Hi @Accio ,

I noticed that the following code works (and returns an invalid `GmtList`).

``` r
suppressPackageStartupMessages(library(BioQC))
gmtFile <- system.file("extdata/exp.tissuemark.affy.roche.symbols.gmt", package="BioQC")
gmt <- readGmt(gmtFile)
gmt[c("Adipose_NGS_RNASEQATLAS_0.6_3", "NONEXISTeNT", "Brain_NGS_RNASEQATLAS_0.6_3")]
#> A gene-set list in GMT format with 3 genesets
#> Gene-sets:
#>   Adipose_NGS_RNASEQATLAS_0.6_3 (Roche,n=28): THRSP,KRT14,APOB,...
#> character(0)
#>   Brain_NGS_RNASEQATLAS_0.6_3 (Roche,n=387): MIR219-2,MIR378B,SLC17A6,...
```

<sup>Created on 2022-01-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Sharing this in case you would like to add some kind of warning in this case. Please feel free to close in case you think it's an expected behavior.

**Comment by Accio** [comment]
thank you @idavydov, a check and a warning was added in commit 3dabe9a, including tests. Thank you for reporting and please let me know if you have other suggestions.

**Comment by idavydov** [comment]
Thanks, @Accio !
